baseURL = "https://arindambhattacharya.github.io/"
languageCode = "en-us"
title = "Arindam's Blog"
theme = "paperesque"
copyright = "© 2026 Arindam Bhattacharya"
paginate = 10

[markup]
  defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
  unsafe = false

[params]

  [[params.menu]]
    name = "Recent Posts"
    url = "posts/"

  [[params.menu]]
    name = "Posts by Tag"
    url = "tags/"

  [[params.menu]]
    name = "About"
    url = "about/"

  [[params.topmenu]]
    name = "rss"
    url = "posts/index.xml"

  [[params.topmenu]]
    name = "github"
    url = "https://github.com/arindambhattacharya"
