baseURL = "https://arindambhattacharya.github.io/"
languageCode = "en-US"
title = "Arindam's Blog"
author = "Arindam Bhattacharya"
copyright = "© 2026 Arindam Bhattacharya"
theme = "hugo-bearblog"
enableRobotsTXT = false

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Personal blog by Arindam Bhattacharya."
  title = "Arindam's Blog"
  dateFormat = "2 January 2006"
  enablePostNavigator = true
  hideMadeWithLine = true

[markup]
  [markup.highlight]
    style = "friendly"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
