#+HTML_MATHJAX: align: left indent: 5em tagside: left font: Neo-Euler
#+TITLE: Problem Description v1
  
* tl;dr
  Create a framework which allows user to tweak knobs of system parameters and give them parameters of the model that meets their requirements. For example, for input specification of: [X gb index space, Y ms average retrieval time, 0.1 fpr] the framework may suggest something like [classifier A with parameter set B with Bloom filter of size C bits]

* Motivation
  Compact data structures like Bloom filters assumes worst case (uniform) data distribution. Our belief is that knowledge about the distribution will help improve the performance (in terms of system parameters like storage or time) of such data structures.

* Problem Setting
  The true data comes from an unknown distribution $f: U \rightarrow L$. We train a model that predicts desired values (e.g. membership in case of Bloom filters or index in case of B-trees). The model gives us a distribution $g: U \rightarrow L$. The knowledge from this distribution is used to enhance the data structure. The hypothesis that we want to test is that the /better/ the classifier is, the more will be the gain from using the knowledge.

* Problem description
  In the given setting setting, traditional data structures, which assumes uniform distribution works with 0 knowledge. An oracle would work with complete knowledge. The use of learned model will place us somewhere in the spectrum. There is a trade off between how high in spectrum we are placed, and how much resources we are spending to get there. Our goal is to allow users to make educated trade offs based on their requirement.
  Based on the above, our goal in threefold:
  - Develop a metric to quantify the /goodness/ of classifier. One way to do this is to measure the distance between the two distributions $f$ and $g$.
  - Give a relationship between classifier parameters and the above mentioned metric, which would then allow us to tweak the classifier to achieve particular result.
  - Finally, give a relationship between the metric and system parameters, which would then lead to a relationship between classifier parameters and system parameters. This will allow end users to select and tweak classifiers based on their needs and restrictions.

* Details
** Developing metric
   The metric should capture the distance between the true data distribution and the distribution given by the classifier. There are various ways of doing this. Some which we plan to explore are:
   - Divergence between the two distributions $f$ and $g$.
   - A bound on the error of the distribution $g$ compared to $f$.
   - For diagnostic purposes, we can use hamming distance to verify our hypothesis in case of binary class (bloom filter).
** Classifier parameters
  The choice of classifier will define the classifier parameters. The dimension for selection of classifiers spans:
  - Type: e.g. linear, quadratic, SVM, neural network
  - Complexity: e.g. number of layers in neural network, type of kernal in SVM.
  - Generalization: e.g: adjusting regularizer, dropout (unlike traditional approaches for classification, our model will run on train data only).
  - Instances: Different instances of parameters once type and complexity is fixed.
** System parameters
   The relationship between classifier parameters and system parameters will give system/database admin the choice to select model. These parameters will be based on applications. The ones we plan to involve are:
   - Memory usage of the model + data structure.
   - Speed improvement by incorporating model
   - Performance of the model + data structure (e.g. fpr of Bloom filter)
