#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org.css">
#+HTML_MATHJAX: align: left indent: 5em tagside: left font: Neo-Euler
#+options: num:2 toc:2 html-postamble:nil
#+SETUPFILE: ../setup/theme-readtheorg.setup
#+title: Reading List
* Random Kernels
** Li, Y., Zhang, K., Wang, J., & Kumar, S. (2019). Learning Adaptive Random Features. (AAAI 2019) [[file:papers/Li%20et%20al.%20-%202017%20-%20Learning%20Adaptive%20Random%20Features.pdf][pdf]]
- The problem is: how to optimize the design of random Fourier features to achieve good kernel approximation on /any input data/ using a low spectral sampling rate?
- Most of the existing works ignore the impact of the input data distribution on the design of the feature map. Instead, the main dependency considered is the relation between the kernel and its /characteristic function/.
- Better kernel approximation doesn't always translate to better generalization.
- To address the (mainly) first issue, authors suggest that the $p(\mathbf{w})$, i.e. the characteristic function of the kernel, should depend on $\mathbf{P}(\mathbf{x})$. (note on notation: the authors use $w$ for the $D$ dimensional /spectral samples/ which were $\omega$ in Rahimi. el. al.)
- They achieve this using the concept of importance sampling
  - $\begin{align*}
    k(\mathbf{x}_1-\mathbf{x}_2)& = \int_{\mathbb{R}_d} \cos(\mathbf{w}^T(\mathbf{x}_1-\mathbf{x}_2))p(\mathbf{w})d\mathbf{w}\\
     & = \int_{\mathbb{R}_d} \cos(\mathbf{w}^T(\mathbf{x}_1-\mathbf{x}_2))\frac{p(\mathbf{w})}{q(\mathbf{w})}q(\mathbf{w})d\mathbf{w}\\
    \end{align*}$
  - Now, consider the representation of $z$. Originally, $\mathbf{z} \equiv \sqrt{\frac{1}{r}}[\cos(\mathbf{w}_1^T\mathbf{x}),\ldots ,\cos(\mathbf{w}_r^T\mathbf{x})]$. Now we write it as $\mathbf{z} \equiv [\sqrt{p_1}\cos(\mathbf{w}_1^T\mathbf{x}),\ldots ,\sqrt{p_r}\cos(\mathbf{w}_r^T\mathbf{x})]$ where $p_j=p(\mathbf{w}_j)/(r.q(\mathbf{w}_j))$. The goal is then to minimize the expected error which now depends on the distribution of input*: $\min_{q(\mathbf{w})}\mathbb{E}_{\mathbf{x}_1, \mathbf{x}_2}\mathbb{E}_{\mathbf{w}_j}|\mathbf{z}(\mathbf{x}_1)\mathbf{z}(\mathbf{x}_2) - k(\mathbf{x}_1-\mathbf{x}_2)|$
  - *$p(\mathbf(w))\propto(e^{-\|\mathbf{w}\|^2} + e^{-(1+2\sigma_0^2)\|\mathbf{w}\|^2})^{1/2}$ where $\mathbf{x}_1-\mathbf{x}_2$ follows the distribution $N(0, \sigma_0^2)$
  - The rest of the paper provides algorithms to efficiently compute the spectral samples and their weights. We learn $p_j$ directly instead of $q(\mathbf(w_j))$ using a loss function which collectively optimizes the supervised learning loss and the kernel approximation loss (EKAL).
  - The authors provide certain bounds on the approximations used to make the optimization of EKAL efficient. No bounds are given regarding performance on classification task, or number of spectral samples needed.
** Rahimi, Ali and Recht, Ben - Random Features for Large-Scale Kernel Machines (NIPS 2008) [[file:papers/Rahimi,%20Recht%20-%202007%20-%20Random%20features%20for%20large-scale%20kernel%20machines.pdf][pdf]]
- Problem is that the methods that operate on the kernel matrix (Gram matrix) of the data scale poorly with the size of the training dataset
- To address this, the authors *convert the training and evaluation of any kernel machine* into the corresponding operations of a linear machine *by mapping data into a relatively low-dimensional randomized feature space*
- Key observation: Any positive definite function $k(x, y)$ with $x, y ∈ \mathbb{R}^d$ defines an inner product and a /lifting/ $\varphi$ so that the inner product between lifted datapoints can be quickly computed as $\langle \varphi(x), \varphi(y)\rangle = k(x, y)$.
- Problem with this is that $\varphi$ can be of high dimension. Therefore, instead of the implicit lifting given by the function $k$, explicitly map the data to a low dimensional /Eucledian inner product space (semi-Hilbert space)/ using randomized feature map $\mathbf{z}: \mathbb{R}^d \rightarrow \mathbb{R}^D$
- To this end, the paper proposes two such random mappings:
  - Random Fourier features - utilizes Bochner's theorem
  - Random binning features - KD-trees
- Random Fourier features
  - Bochner's Theorem: A continuous kernel $k(x, y) = k(x − y)$ on $\mathbb{R}^d$ is positive definite if and only if $k(\delta)$ is the Fourier transform of a non-negative measure.
  - The theorem, along with the fact that kernel $k$ is real lets us create the mapping $z_\omega(x) = \sqrt{2}\cos{\omega'x+b}$ such that $z(x)'z(y) ≈ k(x − y)$
  - This gives us the follwing algorithm:
    - Compute the Fourier transform $p$ of the kernel $k: p(\omega) = \frac{1}{2\pi}\int e^{−j\omega \delta}k(\delta) d\delta$.
    - Draw $D$ /iid/ samples $\omega_1, \ldots , \omega_D \in \mathbb{R}^d$ from $p$ and $D$ /iid/ samples $b_1, . . . , b_D \in \mathbb{R}$ from the uniform distribution on $[0, 2\pi]$.
    - Then, $\mathbf{z} \equiv \sqrt{\frac{2}{D}}[\cos{\omega_1'x+b_1},\ldots ,\cos{\omega_D'x+b_D}]$
  - Paper gives analysis of bound on the error. /Not completely clear/.
- Random binning features:
  - This involves randomly partitioning the input space into axis-parallel grids of /random/ resolution $\delta$ so that /Pr[x and y are in same bin]/ = $k_{hat}(x, y;\delta)$
* Bloom Filters
** The Case for Learned Index Structures. Kraska, T., Beutel, A., Chi, E. H., Dean, J., & Polyzotis, N. (2017)
 Databases use indexes to access data quickly. B-Trees, Hash-maps and Bloom Filters are common techniques to implement indexes. But along with the blackbox view, the databases treat the data as opaque, and apply these indexes blindly without making any assumptions about the data. However, knowing the data distribution can make the data structures more efficient. This is the key idea which the paper applies to the three commonly used data structures.
*** B-Trees
 B-trees provide a hierarchical efficient index. Conceptually, b-tree maps a key to a page. The paper proposes to have a model that performs key to position mapping, and for the error range, a variant of binary search (or expanded ring search) to locate the page is used.
*** Hash maps
 Hash maps are used for point-lookup queries. The application of model in this is case is straigtforward prediction of CDF of the distribution. Once we have the CDF, the target is located simply by calculating CDF*key*record-size.
*** Bloom filters
 Bloom filters are used to answer membership queries. The paper suggests two ways to use the distribution to enhance Bloom filter.
 - The bloom filter can be replaced with a binary classifier model that answers yes or no for a membership query. To preserve the /no false negative/ property, an overflow bloom bloom filter is augmented to the model.
 - Instead of a binary classifier replacing Bloom filter, we use a model to replace the hashing function of the Bloom filter. The idea here is that the collision between positive and negative queries will be minimized as they will be indexed in the two extremes of the Bloom filter.

** A Model for Learned Bloom Filters, and Optimizing by Sandwiching. Mitzenmacher, M. (2019)
 In the /learned Bloom filter/, the purpose of the backup bloom filter is to filter out the false negatives. This paper extends the idea to add an addition Bloom filter to filter out negatives /before/ feeding them into the classifier. Consequently the number of false negatives decreases and the size of the overflow Bloom filter can be much smaller.

 In addition to the introduction of /sandwiched learned Bloom filter/, the paper also notes certain issues with the analysis of LBF that does not appear in the standard Bloom filter. These are:
 - The false positive rate in LBF is dependent on the query. Any guarantee assumes same distribution of query and test elements.
 - The false positives are introduced by two sources. The model and the overflow Bloom filter.

 The appendix of the paper introduces /Bloomier filter/, a data structure that not only returns yes/no, but a value associated with the element if yes.

** The Potential of Learned Index Structures for Index Compression. Oosterhuis, H., Culpepper, J. S., & de Rijke, M. (2018)
 This paper applies the idea of learned indexes in the context of search. It explores i. How learned indexes can be used instead of traditional indexes? ii. What space befinits do such compressed index may potentially provide?
 The traditional task is:
 - Given a n-word query $q_1, ..., q_n$, look up an inverted document index to find set of documents where each of the query word occurs.
 Here, the paper proposes that the inverted document index can be replaced by a function $f(t, d) = \begin{cases} 1,\ t\in d \\ 0,\ t\notin d \end{cases}$.
 Quote from the paper: /In theory any deep neural network that is expressive enough could be optimized for an entire document collection without any errors. In practice, such a model has to be relatively sizeable and requires a very long period of optimization. Therefore, one may choose to compromise some correctness for practical reasons./
 # * Improving Online Algorithms via ML Predictions. Purohit, M., Svitkina, Z., & Kumar, R. (2018)
